apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  predictor:
    model:
      modelFormat:
        name: pytorch
      protocolVersion: v2
      resources:
        limits:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
        requests:
          cpu: "8"
          memory: 32Gi
          nvidia.com/gpu: "1"
      storageUri: pvc://{{ .Release.Name }}-claim/{{ .Values.model }}